apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: kaf3
 annotations:
   volume.beta.kubernetes.io/storage-class: kafka04
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 395Mi
