apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.4.2
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  namespace: smp-dev
  name: kibana
  labels:
    name: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
    name: kibana
  selector:
    name: kibana