apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: digitaltwin-squid
  name: digitaltwin-squid
spec:
  ports:
  - name: "4840"
    port: 4840
    targetPort: 4840
  selector:
    io.kompose.service: digitaltwin-squid
  type: LoadBalancer
status:
  loadBalancer: {}
