apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: bootstrap.memory_lock
          value: "true"
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  namespace: smp-dev
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  selector:
    name: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: elasticsearch
#  clusterIP: 10.244.171.239
#  loadBalancerIP: 78.11.24.19
#  type: LoadBalancer
#status:
#  loadBalancer:
#    ingress:
#    - ip: 146.148.47.155