apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: squid-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 224Mi

---

apiVersion: v1
kind: Service
metadata:
  name: squid-service
spec:
  ports:
  - name: "3128"
    port: 3128
    targetPort: 3128
  selector:
        app: squid
  type: LoadBalancer
status:
  loadBalancer: {}
---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: squid-deployment
spec:
  serviceName: squid-service
  selector:
    matchLabels:
      app: squid
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: squid
    spec:
      nodeName: pg-aicon-storage-1
      containers:
      - env:
        - name: SQUID_LISTEN
          value: 127.0.0.1
        - name: SQUID_PORT
          value: "3128"
        image: squid:test
        name: squid-deployment
        ports:
        - containerPort: 3128
        volumeMounts:
        - name: squid-vol
          mountPath: /var/spool/squid
        resources: {}
      restartPolicy: Always
      volumes:
        - name: squid-vol
          persistentVolumeClaim:
            claimName: squid-pvc  
