descriptor_extension: yml
package:
  description: Project for the development of vrouter + fsm service
  maintainer: Miguel Mesquita, Alticelabs 
  name: tango-etsi-plug-vrouter-fsm
  vendor: eu.sonata-nfv
  version: '0.1'
version: '0.1'
