apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_LISTEN
          value: 127.0.0.1
        - name: INFLUXDB_PORT
          value: "8086"
        image: influxdb:latest
        name: influxdb
        ports:
        - containerPort: 8086
        resources: {}
      restartPolicy: Always
status: {}
