apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: squid03
 annotations:
   volume.beta.kubernetes.io/storage-class: squid03
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 222Mi
