descriptor_extension: yml
version: '0.5'
files:
- path: nsd/nsd_smpilot_ns2_emulator.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
- path: vnfd/vnfd_dt_emulator.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: vnfd/vnfd_mdc_emulator.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: vnfd/vnfd_rtr_emulator.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
package:
  name: tng-smpilot-ns2-emulator
  version: '0.1'
  maintainer: Stefan Schneider (Paderborn University)
  vendor: eu.5gtango
  description: 'Smart manufacturing pilot: Machine interconnection service (NS2) for
    vim-emu.'
uuid: cab5863e-86ba-4a0e-8e6f-8ce8afd0ff0b
