apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.44.0.1:8080"
  restuser: "admin"
  restuserkey: "My Secret"
