kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-broker0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      nodeName: pg-aicon-storage-2
      containers:
      - name: kafka
        image: kafka:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: PLAINTEXT://10.0.0.80:9092
        - name: KAFKA_BROKER_ID
          value: "0"
