apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "31090"
    port: 31090
    targetPort: 31090
  selector:
    io.kompose.service: kafka
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
    spec:
      nodeName: pg-aicon-storage-3
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://172.17.42.1:9092,EXTERNAL://10.0.0.81:31090
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: EXTERNAL
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092,EXTERNAL://:31090
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: kafka:dt
        name: kaf004
        ports:
        - containerPort: 9092
        - containerPort: 31090
        volumeMounts:
        - name: kafka-vol
          mountPath: /tmp/kafka-logs
        resources: {}
      volumes:
      - name: kafka-vol
        persistentVolumeClaim:
          claimName: kafka1               
      restartPolicy: Always
status: {}