apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka0
    spec:
      nodeName: pg-aicon-storage-1
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://172.17.42.1:9092,EXTERNAL://10.0.0.80:31090
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: EXTERNAL
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092,EXTERNAL://:31090
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: kafka:f
        name: kafka0
        ports:
        - containerPort: 9092
        - containerPort: 31090
        resources: {}
      restartPolicy: Always
status: {}
