version: '2'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.2
    container_name: filebeat
    environment:
      - setup.kibana.host=kibana:5601
      - output.logstash.hosts=["localhost:9200"]
      #- output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - sdata:/usr/share/filebeat/data
    #ports:
      #- 9200:9200
    networks:
      - smpnet

volumes:
  sdata:
    driver: local

networks:
  smpnet:
    driver: bridge

# [CREDITS](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html)
