---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitaltwinnew
  labels:
    app: digitaltwinnew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digitaltwinnew
  template:
    metadata:
      labels:
        app: digitaltwinnew
    spec:
      nodeName: pg-aicon-storage-2
      containers:
      - image: digitaltwin:influx
        name: digitaltwinnew
        env:
        - name: OPCUA_HOST
          value: 0.0.0.0
        ports:
        - containerPort: 4840
        - containerPort: 15001
      restartPolicy: Always