apiVersion: v1
kind: Service
metadata:
  labels:
    app: digitaltwinnew
  name: digitaltwinnew
spec:
  selector:
    app: digitaltwinnew
  ports:
    - name: "4840"
      port: 4840
      targetPort: 4840
    - name: "15001"
      port: 15001
      targetPort: 15001