apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdbnew
  name: influxdbnew
spec:
  selector:
    app: influxdbnew
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
    - name: "9273"
      port: 9273
      targetPort: 9273