---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitaltwinnew
  labels:
    app: digitaltwinnew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digitaltwinnew
  template:
    metadata:
      labels:
        app: digitaltwinnew
    spec:
      nodeName: pg-aicon-storage-6
      containers:
      - image: digitaltwin:influx
        name: digitaltwinnew
        env:
        - name: OPCUA_HOST
          value: 0.0.0.0
        ports:
        - containerPort: 4840
        - containerPort: 15001
      restartPolicy: Always
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdbnew
  labels:
    app: influxdbnew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdbnew
  template:
    metadata:
      labels:
        app: influxdbnew
    spec:
      nodeName: pg-aicon-storage-5
      containers:
      - image: influxdb:dev
        name: influxdbnew
        ports:
        - containerPort: 8086
        - containerPort: 9273
        volumeMounts:
        - name: influxdbnew-vol
          mountPath: /var/lib/influxdb
        resources: {}
      volumes:
      - name: influxdbnew-vol
        persistentVolumeClaim:
          claimName: gluster1
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb-connector
  name: influxdb-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-connector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-connector
    spec:
      nodeName: pg-aicon-storage-5
      containers:
      - image: connector:dev
        name: influxdb-connector
        env:
        - name: INFLUXDB_HOST
          value: influxdbnew
        - name: OPCUA_SERVER
          value: digitaltwinnew
        volumeMounts:
         - name: csv-volume
           mountPath: /app/csv/
      volumes:
        - name: csv-volume
          hostPath:
            path: /tmp/
            type: Directory
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: digitaltwinnew
  name: digitaltwinnew
spec:
  selector:
    app: digitaltwinnew
  ports:
    - name: "4840"
      port: 4840
      targetPort: 4840
    - name: "15001"
      port: 15001
      targetPort: 15001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdbnew
  name: influxdbnew
spec:
  selector:
    app: influxdbnew
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
    - name: "9273"
      port: 9273
      targetPort: 9273
