---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdbnew
  labels:
    app: influxdbnew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdbnew
  template:
    metadata:
      labels:
        app: influxdbnew
    spec:
      nodeName: pg-aicon-storage-3
      containers:
      - image: influxdb:dev
        name: influxdbnew
        ports:
        - containerPort: 8086
        - containerPort: 9273
        volumeMounts:
        - name: influxdbnew-vol
          mountPath: /var/lib/influxdb
        resources: {}
      volumes:
      - name: influxdbnew-vol
        persistentVolumeClaim:
          claimName: gluster1
      restartPolicy: Always
